name: Run unit tests

on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test
